#!/bin/bash

./cropNonChar.sh Slime.jpg
./cropNonChar.sh Fairy.jpg
./cropNonChar.sh JrNecki.jpg
./cropNonChar.sh Octopus.jpg
./cropNonChar.sh RedSnail.jpg
./cropNonChar.sh WildBoar.jpg
./cropNonChar.sh MagicClaw.jpg
./cropNonChar.sh RibbonPig.jpg
./cropNonChar.sh DarkAxeStump.jpg
./cropNonChar.sh GreenMushroom.jpg
./cropNonChar.sh OrangeMushroom.jpg
./cropNonChar.sh EmeraldEarrings.jpg
./cropNonChar.sh FireBoar.jpg
./cropNonChar.sh Grizzly.jpg
./cropNonChar.sh BlockGolem.jpg
./cropNonChar.sh StoneGolem.jpg
./cropNonChar.sh Tauromacis.jpg
./cropNonChar.sh YetiPepe.jpg
./cropNonChar.sh Resting.jpg
./cropNonChar.sh BattleShield.jpg
./cropNonChar.sh TheNineDragons.jpg
./cropNonChar.sh Drake.jpg
./cropNonChar.sh GreenTrixter.jpg
./cropNonChar.sh JrBoogie.jpg
./cropNonChar.sh LunarPixie.jpg
./cropNonChar.sh Stirge.jpg
./cropNonChar.sh Tweeter.jpg
./cropNonChar.sh ArrowBlow.jpg
./cropNonChar.sh RainOfArrows.jpg
./cropNonChar.sh SoulArrow.jpg
./cropNonChar.sh PowerKnockBack.jpg
./cropNonChar.sh GoldenCrow.jpg
./cropNonChar.sh BattleBow.jpg
./cropNonChar.sh Avenger.jpg
./cropNonChar.sh DoubleStrike.jpg
./cropNonChar.sh Buffy.jpg
./cropNonChar.sh Cico.jpg
./cropNonChar.sh Croco.jpg
./cropNonChar.sh Krappy.jpg
./cropNonChar.sh Krip.jpg
./cropNonChar.sh Lorang.jpg
./cropNonChar.sh CurseEye.jpg
./cropNonChar.sh HornedMushroom.jpg
./cropNonChar.sh PlatoonChronos.jpg
./cropNonChar.sh ItemTrade.jpg
./cropNonChar.sh EnergyBolt.jpg
./cropNonChar.sh Heal.jpg
./cropNonChar.sh SideQuest.jpg
./cropNonChar.sh BellflowerRoot.jpg
./cropNonChar.sh Lioner.jpg
./cropNonChar.sh PeachMonkey.jpg
./cropNonChar.sh ZetaGray.jpg
./cropNonChar.sh ZombieLupin.jpg
./cropNonChar.sh CoconutKnife.jpg
./cropNonChar.sh JrYeti.jpg
./cropNonChar.sh Pepe.jpg
./cropNonChar.sh Sentinel.jpg
./cropNonChar.sh Cerebes.jpg
./cropNonChar.sh ChiefGray.jpg
./cropNonChar.sh RedNight.jpg
./cropNonChar.sh RedApprenticeHat.jpg
./cropNonChar.sh Lucida.jpg
./cropNonChar.sh OfficerSkeleton.jpg
./cropNonChar.sh Hector.jpg
./cropNonChar.sh SoulTeddy.jpg
./cropNonChar.sh Focus.jpg
./cropNonChar.sh SerpentsTongue.jpg
./cropNonChar.sh Doombringer.jpg
./cropNonChar.sh MapleStaff.jpg
./cropNonChar.sh KnowledgeIsPower.jpg
./cropNonChar.sh Pull.jpg
./cropNonChar.sh Meditation.jpg
./cropNonChar.sh Seacle.jpg
./cropNonChar.sh Propelly.jpg
./cropNonChar.sh PinkTeddy.jpg
./cropNonChar.sh RiskyShot.jpg
./cropNonChar.sh BloodSlain.jpg
./cropNonChar.sh Swipe.jpg
./cropNonChar.sh ThunderBolt.jpg
./cropNonChar.sh EvilTale.jpg
./cropNonChar.sh KumbiThrowingStar.jpg
./cropNonChar.sh DarkShadow.jpg
./cropNonChar.sh BlackRobinHat.jpg
./cropNonChar.sh Teleport.jpg
./cropNonChar.sh BlueNightfox.jpg

./cropChar.sh Sherman.jpg
./cropChar.sh Nixie.jpg
./cropChar.sh Ivan.jpg
./cropChar.sh Maya.jpg
./cropChar.sh Skyhawk.jpg
./cropChar.sh Stormwind.jpg
./cropChar.sh Mistmoon.jpg
./cropChar.sh Starblade.jpg
