#!/bin/bash

curl -o Slime.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/slime.png
curl -o Fairy.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/fairy.png
curl -o JrNecki.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/jrnecki.png
curl -o Octopus.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/octopus.png
curl -o RedSnail.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/redsnail.png
curl -o WildBoar.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/wildboar.png
curl -o MagicClaw.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/magicclaw.png
curl -o RibbonPig.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/ribbonpig.png
curl -o DarkAxeStump.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/darkaxestump.png
curl -o GreenMushroom.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/greenmushroom.png
# curl -o OrangeMushroom.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/orangemushroom.png
curl -o EmeraldEarrings.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/emeraldearrings.png
curl -o FireBoar.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/fireboar.png
curl -o Grizzly.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/grizzly.png
curl -o BlockGolem.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/blockgolem.png
curl -o StoneGolem.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/stonegolem.png
curl -o Tauromacis.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/tauromacis.png
curl -o YetiPepe.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/yetipepe.png
curl -o Resting.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/resting.png
curl -o BattleShield.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/battleshield.png
curl -o TheNineDragons.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/theninedragons.png
curl -o Drake.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/drake.png
curl -o GreenTrixter.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/greentrixter.png
curl -o JrBoogie.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/jrboogie.png
curl -o LunarPixie.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/lunarpixie.png
curl -o Stirge.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/stirge.png
curl -o Tweeter.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/tweeter.png
curl -o ArrowBlow.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/arrowblow.png
curl -o RainOfArrows.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/rainofarrows.png
curl -o SoulArrow.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/soularrow.png
curl -o PowerKnockBack.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/powerknockback.png
curl -o GoldenCrow.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/goldencrow.png
curl -o BattleBow.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/battlebow.png
curl -o Avenger.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/avenger.png
curl -o DoubleStrike.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/doublestrike.png
curl -o Buffy.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/buffy.png
curl -o Cico.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/cico.png
curl -o Croco.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/croco.png
curl -o Krappy.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/krappy.png
curl -o Krip.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/krip.png
curl -o Lorang.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/lorang.png
curl -o CurseEye.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/cursedeye.png
curl -o HornedMushroom.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/hornedmushroom.png
curl -o PlatoonChronos.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/platoonchronos.png
curl -o ItemTrade.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/itemtrade.png
curl -o EnergyBolt.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/energybolt.png
curl -o Heal.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/heal.png
curl -o SideQuest.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/sidequest.png
curl -o BellflowerRoot.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/bellflowerroot.png
curl -o Lioner.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/lioner.png
curl -o PeachMonkey.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/peachmonkey.png
curl -o ZetaGray.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/zetagrey.png
curl -o ZombieLupin.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/zombielupin.png
curl -o CoconutKnife.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/coconutknife.png
curl -o JrYeti.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/jryeti.png
curl -o Pepe.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/pepe.png
curl -o Sentinel.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/sentinel.png
curl -o Cerebes.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/cerebes.png
curl -o ChiefGray.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/chiefgray.png
curl -o RedNight.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/rednight.png
curl -o RedApprenticeHat.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/redapprenticehat.png
curl -o Lucida.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/lucida.png
curl -o OfficerSkeleton.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/officerskeleton.png
curl -o Hector.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/hector.png
curl -o SoulTeddy.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/soulteddy.png
curl -o Focus.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/focus.png
curl -o SerpentsTongue.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/serpentstongue.png
curl -o Doombringer.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/doombringer.png
curl -o MapleStaff.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/maplestaff.png
curl -o KnowledgeIsPower.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/knowledgeispower.png
curl -o Pull.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/pull.png
curl -o Meditation.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/meditation.png
curl -o Seacle.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/seacle.png
curl -o Propelly.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/propelly.png
curl -o PinkTeddy.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/pinkteddy.png
curl -o RiskyShot.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/riskyshot.png
curl -o BloodSlain.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/bloodsain.png
curl -o Swipe.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/swipe.png
curl -o ThunderBolt.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/thunderbolt.png
curl -o EvilTale.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/eviltale.png
curl -o KumbiThrowingStar.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/kumbithrowingstar.png
curl -o DarkShadow.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/darkshadow.png
curl -o BlackRobinHat.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/blackrobinhat.png
curl -o Teleport.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/teleport.png
curl -o BlueNightfox.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/bluenightfox.png

curl -o Sherman.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/sherman.png
curl -o Nixie.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/nixie.png
curl -o Ivan.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/ivan.png
curl -o Maya.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/maya.png
curl -o Skyhawk.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/skyhawk.png
curl -o Stormwind.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/stormwind.png
curl -o Mistmoon.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/mistmoon.png
curl -o Starblade.png http://34.71.53.141/card-images/MapleStory/MapleStory/sets/setimages/Set1/starblade.png
