#!/bin/bash

mv sized_Slime.png Slime.png
mv sized_Fairy.png Fairy.png
mv sized_JrNecki.png JrNecki.png
mv sized_Octopus.png Octopus.png
mv sized_RedSnail.png RedSnail.png
mv sized_WildBoar.png WildBoar.png
mv sized_MagicClaw.png MagicClaw.png
mv sized_RibbonPig.png RibbonPig.png
mv sized_DarkAxeStump.png DarkAxeStump.png
mv sized_GreenMushroom.png GreenMushroom.png
mv sized_OrangeMushroom.png OrangeMushroom.png
mv sized_EmeraldEarrings.png EmeraldEarrings.png
mv sized_FireBoar.png FireBoar.png
mv sized_Grizzly.png Grizzly.png
mv sized_BlockGolem.png BlockGolem.png
mv sized_StoneGolem.png StoneGolem.png
mv sized_Tauromacis.png Tauromacis.png
mv sized_YetiPepe.png YetiPepe.png
mv sized_Resting.png Resting.png
mv sized_BattleShield.png BattleShield.png
mv sized_TheNineDragons.png TheNineDragons.png
mv sized_Drake.png Drake.png
mv sized_GreenTrixter.png GreenTrixter.png
mv sized_JrBoogie.png JrBoogie.png
mv sized_LunarPixie.png LunarPixie.png
mv sized_Stirge.png Stirge.png
mv sized_Tweeter.png Tweeter.png
mv sized_ArrowBlow.png ArrowBlow.png
mv sized_RainOfArrows.png RainOfArrows.png
mv sized_SoulArrow.png SoulArrow.png
mv sized_PowerKnockBack.png PowerKnockBack.png
mv sized_GoldenCrow.png GoldenCrow.png
mv sized_BattleBow.png BattleBow.png
mv sized_Avenger.png Avenger.png
mv sized_DoubleStrike.png DoubleStrike.png
mv sized_Buffy.png Buffy.png
mv sized_Cico.png Cico.png
mv sized_Croco.png Croco.png
mv sized_Krappy.png Krappy.png
mv sized_Krip.png Krip.png
mv sized_Lorang.png Lorang.png
mv sized_CurseEye.png CurseEye.png
mv sized_HornedMushroom.png HornedMushroom.png
mv sized_PlatoonChronos.png PlatoonChronos.png
mv sized_ItemTrade.png ItemTrade.png
mv sized_EnergyBolt.png EnergyBolt.png
mv sized_Heal.png Heal.png
mv sized_SideQuest.png SideQuest.png
mv sized_BellflowerRoot.png BellflowerRoot.png
mv sized_Lioner.png Lioner.png
mv sized_PeachMonkey.png PeachMonkey.png
mv sized_ZetaGray.png ZetaGray.png
mv sized_ZombieLupin.png ZombieLupin.png
mv sized_CoconutKnife.png CoconutKnife.png
mv sized_JrYeti.png JrYeti.png
mv sized_Pepe.png Pepe.png
mv sized_Sentinel.png Sentinel.png
mv sized_Cerebes.png Cerebes.png
mv sized_ChiefGray.png ChiefGray.png
mv sized_RedNight.png RedNight.png
mv sized_RedApprenticeHat.png RedApprenticeHat.png
mv sized_Lucida.png Lucida.png
mv sized_OfficerSkeleton.png OfficerSkeleton.png
mv sized_Hector.png Hector.png
mv sized_SoulTeddy.png SoulTeddy.png
mv sized_Focus.png Focus.png
mv sized_SerpentsTongue.png SerpentsTongue.png
mv sized_Doombringer.png Doombringer.png
mv sized_MapleStaff.png MapleStaff.png
mv sized_KnowledgeIsPower.png KnowledgeIsPower.png
mv sized_Pull.png Pull.png
mv sized_Meditation.png Meditation.png
mv sized_Seacle.png Seacle.png
mv sized_Propelly.png Propelly.png
mv sized_PinkTeddy.png PinkTeddy.png
mv sized_RiskyShot.png RiskyShot.png
mv sized_BloodSlain.png BloodSlain.png
mv sized_Swipe.png Swipe.png
mv sized_ThunderBolt.png ThunderBolt.png
mv sized_EvilTale.png EvilTale.png
mv sized_KumbiThrowingStar.png KumbiThrowingStar.png
mv sized_DarkShadow.png DarkShadow.png
mv sized_BlackRobinHat.png BlackRobinHat.png
mv sized_Teleport.png Teleport.png
mv sized_BlueNightfox.png BlueNightfox.png

mv sized_Sherman.png Sherman.png
mv sized_Nixie.png Nixie.png
mv sized_Ivan.png Ivan.png
mv sized_Maya.png Maya.png
mv sized_Skyhawk.png Skyhawk.png
mv sized_Stormwind.png Stormwind.png
mv sized_Mistmoon.png Mistmoon.png
mv sized_Starblade.png Starblade.png
